In [1]:
import torch

In [2]:
import torch.nn as nn

In [3]:
encoder_layer = nn.TransformerEncoderLayer(d_model=768, nhead=8, dim_feedforward=1024)
transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=2)

In [4]:
src = torch.rand(512, 256, 768)
out = transformer_encoder(src)

out.shape

torch.Size([512, 256, 768])

In [5]:
b = out[:,0,:]
b.shape

torch.Size([512, 768])

In [27]:
weights = torch.rand(32, 768)
emb = nn.Embedding(34, 768)

In [28]:
weights

tensor([[0.3551, 0.4667, 0.2254,  ..., 0.3689, 0.4831, 0.6095],
        [0.2903, 0.0490, 0.2537,  ..., 0.3775, 0.3358, 0.5252],
        [0.4214, 0.4785, 0.7752,  ..., 0.8758, 0.8985, 0.8920],
        ...,
        [0.3350, 0.7590, 0.5379,  ..., 0.1325, 0.9690, 0.9358],
        [0.3238, 0.1922, 0.7860,  ..., 0.4943, 0.8964, 0.5433],
        [0.2255, 0.8967, 0.6095,  ..., 0.0406, 0.5915, 0.4774]])

In [29]:
idx = torch.tensor([[0, 31],[32,33]])
emb(idx)

tensor([[[ 0.3559, -0.0227,  1.0181,  ..., -0.1432,  1.6440,  0.2354],
         [ 0.0597,  1.7064, -0.3051,  ..., -0.2558,  1.1282, -0.7924]],

        [[-0.8913,  0.4222,  1.7534,  ...,  0.8478,  1.4343, -0.0596],
         [ 1.2938,  0.7136,  0.3205,  ...,  0.3385,  0.0960, -0.2269]]],
       grad_fn=<EmbeddingBackward>)

In [30]:
emb.weight.data[:32, :] = weights

In [32]:
emb(idx)

tensor([[[ 0.3551,  0.4667,  0.2254,  ...,  0.3689,  0.4831,  0.6095],
         [ 0.2255,  0.8967,  0.6095,  ...,  0.0406,  0.5915,  0.4774]],

        [[-0.8913,  0.4222,  1.7534,  ...,  0.8478,  1.4343, -0.0596],
         [ 1.2938,  0.7136,  0.3205,  ...,  0.3385,  0.0960, -0.2269]]],
       grad_fn=<EmbeddingBackward>)

In [11]:
a = torch.tensor([[0.2, 0.4], [0.5, 1]])
a

tensor([[0.2000, 0.4000],
        [0.5000, 1.0000]])

In [6]:
multihead_attn = nn.MultiheadAttention(embed_dim=768, num_heads = 8, kdim=96, vdim=96)

In [14]:
x = torch.rand(32, 2, 96)
y = torch.rand(32, 2, 768)

In [15]:
attn_output, attn_output_weights = multihead_attn(query=y, key=x, value=x)

In [16]:
attn_output.shape, attn_output_weights.shape

(torch.Size([32, 2, 768]), torch.Size([2, 32, 32]))

In [33]:
import os
import sys

"append parent directory so that we can import sibling module"

parent_dir = os.path.dirname(os.path.abspath('.'))
sys.path.append(parent_dir)

In [34]:
import numpy as np
from data_loader.rating_loader import data_processing, load_train_data, load_tr_te_data

In [35]:
processed_data_dir = "../data/processed/4_5_5_False_15000"

In [37]:
n_items = 17493

In [38]:
train_data = load_train_data(os.path.join(processed_data_dir, 'train.csv'), n_items)
vad_data_tr, vad_data_te = load_tr_te_data(os.path.join(processed_data_dir, 'validation_tr.csv'),
                                           os.path.join(processed_data_dir, 'validation_te.csv'),
                                           n_items)

In [40]:
train_data.shape

(193924, 17493)

In [41]:
vad_data_tr.shape, vad_data_te.shape

((15000, 17493), (15000, 17493))

In [42]:
type(train_data)

scipy.sparse.csr.csr_matrix

In [45]:
train_data.nnz

11117298

In [46]:
rows, cols = train_data.nonzero()

In [56]:
train_data = np.split(train_data.indices, train_data.indptr)[1:-1]
vad_data_tr = np.split(vad_data_tr.indices, vad_data_tr.indptr)[1:-1]
vad_data_te = np.split(vad_data_te.indices, vad_data_te.indptr)[1:-1]

In [57]:
vad_data_te[0]

array([145, 715, 767, 878], dtype=int32)

In [59]:
vad_data_tr[0]

array([   3,  153,  181,  251,  259,  262,  304,  320,  336,  366,  671,
        804,  832,  901,  950, 1016, 1772, 2019, 2102, 3007], dtype=int32)

In [61]:
torch.tensor([[1,2,3], [1,4]])

ValueError: expected sequence of length 3 at dim 1 (got 2)

In [62]:
mask = torch.zeros(3, 5)
mask

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [65]:
indices = [[1,2], [0,3,4], [0,1,2,3]]

mask.scatter_(2, indices, 1.)

TypeError: scatter_() received an invalid combination of arguments - got (int, list, float), but expected one of:
 * (int dim, Tensor index, Tensor src)
      didn't match because some of the arguments have invalid types: (int, list, float)
 * (int dim, Tensor index, Tensor src, *, str reduce)
 * (int dim, Tensor index, Number value)
      didn't match because some of the arguments have invalid types: (int, list, float)
 * (int dim, Tensor index, Number value, *, str reduce)


In [68]:
np.inf

inf

In [83]:
target = np.zeros((3, 5))
pred = torch.zeros(3, 5)
vad_data_te = [[1,2], [0,3,4], [0,1,2,3]]
for i in range(target.shape[0]):
    target[i, vad_data_te[i]] = 1.0
    # pred[i, batch.idx_wo_pad[i]] = -10
target

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [1., 1., 1., 1., 0.]])

In [92]:
target

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [1., 1., 1., 1., 0.]])

In [94]:
from scipy import sparse

In [95]:
target_s = sparse.csr_matrix(target) 
target_s.shape

(3, 5)

In [96]:
target_s.getnnz(axis=1)

array([2, 3, 4], dtype=int32)

In [97]:
(target_s > 0).toarray()

array([[False,  True,  True, False, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True,  True, False]])

In [69]:
from torch.nn.utils.rnn import pad_sequence

In [72]:
vad_data_te = [torch.tensor([1,2]), torch.tensor([0,3,4]), torch.tensor([0,1,2,3])]

In [76]:
a = pad_sequence(vad_data_te, True, padding_value=5)
a

tensor([[1, 2, 5, 5],
        [0, 3, 4, 5],
        [0, 1, 2, 3]])

In [74]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [75]:
7%1

0

In [77]:
torch.zeros_like(a)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [78]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [87]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [90]:
[1] + b.tolist() + [3]

[1, 1, 2, 3, 3]

In [ ]:
b.